language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE robo_report_test;' -U postgres
script:
- npm run eslint
- npm test
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: FUYFtim6bsBk+8g05Dr/LkI/qspPj0Pi+vO4bXu/D/XV3E7S4NZScz21SriuBuu8B15lN+g97NNCj/tN7M2vbe+mW8l6bUQK62ez5AFJkDQALHItduHM6cCLqcMUKVpBcB7jF5YhWpnAsZdyK+mLEHXGaMKzddWr+01/tdDPqpYzeN/qq0hFkDNyixYDUoDSJJr0ULtTyjFXrQw5imfQ/CPIjYQnVTOSZKbbFNFiXEfteiya+uZJtm+E9OmuHRczrMOB+TmGDxREKk3SMur5n5vApnksRKk6VIhe08SI/0V99O+RMQy8L6PXVq9B9JQzOigJf8hB6CaKoBxVv+B39Tq8OLTM8eJAHadVPmioMxOsKs7+8CS/u+/uxtnr8GiXKLHCvKA1MjF1zWIdoyGCHja8UG4huzWOON7BmQX2Xiq+hYA1uj2fWtXo1drStXcL7pXI6rMdnJAsswEAzn+R5BBqINQeiTJAy2WVgUEEG7N2cMMI1aPo8ly1EFcNxS/AcVdcu+C6uU0VAijP+3/5/GOh1t7ope6++pHz6zIvpl3cLKqXXC8frGakhLYcbFw92CazN+L7OkG5Mr1qx8AKwggeabKra4/humBKk9/QsHqqTZDtytPeCt3Yq9QoHIrwwSwmNz+hnrPByLaom5CTf01Ct3IGrQwfuup0RMF/AeI=
  app: roboreport-api
  on:
    repo: rennmatthewp/roboReport
env:
  matrix:
    secure: XIrQfdhGYgztqOun3DmGd2yFGU6KmGLDCrVXNhb1QnWNAHO6XQNMJTHLeTXqL8h6wYMTndj8VwBlQmc1R0ro0ppSLjB6gv6fsSNQHAEaksokyupGP0Z/zE643t/gkpOFYcD5Fft7forh/7NQ/5WrKemFyS/U+PY78twajdZovy8loGOVACzzXuw/flrP3AjYPEniB1E9bj6ZV5PRjSVSnYu6P+/qQgvB2CH3032KxPuyfPP+CIHl6OCD63xmssj3Kv7Gp9yq1GG/x04CKm2puDE+b/JmBohJ2AJHpUq/BI9gIUDRmN4JLeCi5zuWcVnY1CRu3DCgYZv17YM/CeR4adWm36hJV+Py42xsZGtOot6zCUjxDJ7X+LZm8linSdt6xBeAkQHrigf+3aD6s0WCpFXK+zH4jzyCkNIybFWxJ1Ld18ne+Bh14KVlmDogUbi4iiqCplNM3WlonKPdWok/X7EicpGL7lSyv6AbcJMRoxPQCzmQkIczGVuFGBpXcfCkyxeUjRq+WRJM3xpFnhm6AlF3Ws5FabS5V1Qw+67+sdGmFy80ia9n1fzTiQT94bquGBjL46gD2qwLn4z4H340gxm3gnjLKB1jZXOHSOIsrTBhulnKHg213rDLPonvHU48xaZa93W/T3bdtnrEV9Q66xzA5eatZKTVFTudzJwxUts=
